base: '%env(SITE_INTRODUCTION_BASE)%'
baseVariants: {  }
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=2'
languages:
  -
    languageId: '0'
    title: English
    navigationTitle: English
    base: /
    locale: en_US.UTF8
    iso-639-1: en
    hreflang: en-US
    direction: ltr
    typo3Language: default
    flag: us
    enabled: true
  -
    languageId: '2'
    title: German
    navigationTitle: Deutsch
    base: /de/
    locale: de_DE.UTF8
    iso-639-1: de
    hreflang: de-DE
    direction: ltr
    typo3Language: de
    flag: de
    fallbackType: fallback
    fallbacks: '0'
    enabled: true
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/"
websiteTitle: ''
routeEnhancers:
  ApplyRoutesCollection:
    type: Routes
