name: tests

on:
  push:
    branches:
      - v11

jobs:
  testsuite:
    name: Testsuit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@tests-v11

      - name: Start DDEV
        uses: jonaseberle/github-action-setup-ddev@v1

      - name: Import database
        run: ddev import-db --src=./dump.sql

      - name: Install composer packages
        run: ddev composer install --prefer-dist

      - name: Allow public access of var folder
        run: sudo chmod 0777 ./var

      - name: Psalm
        run: ddev exec bin/psalm

      - name: Unit test suit
        run: ddev exec bin/phpunit -c public/typo3conf/ext/flogin/Tests/Build/UnitTests.xml

      - name: Functional test suit
        run: ddev exec bin/phpunit -c public/typo3conf/ext/flogin/Tests/Build/FunctionalTests.xml

      - name: Acceptance General
        run: ddev exec bin/codecept run acceptance -f -c public/typo3conf/ext/flogin/Tests/codeception.yml --env github

      - name: Acceptance API
        run: ddev exec bin/codecept run acceptance -f -c public/typo3conf/ext/flogin/Tests/api.suite.yml --env github
        if: ${{ false }}

      - name: Acceptance Backend
        run: ddev exec bin/codecept run acceptance -f -c public/typo3conf/ext/flogin/Tests/Backend.suite.yml --env github
        if: ${{ false }}
